# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(blank=True, default=b'', max_length=250)),
                ('last_name', models.CharField(blank=True, default=b'', max_length=250)),
                ('last_password_change', models.DateTimeField(blank=True,
                                                              default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
