# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('log_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=10240, null=True)),
                ('extra', models.CharField(blank=True, max_length=10240, null=True)),
            ],
            options={
                'verbose_name': 'Central Error Log',
                'verbose_name_plural': 'Central Error Logs',
            },
        ),
    ]
